version: '3.4'

services:
  productmanagerdb:
    container_name: productmanagerdb
    environment:
      SA_PASSWORD: "SwN12345678"
      ACCEPT_EULA: "Y"
    restart: always
    ports:
      - "1433:1433"


  productmanager.api:
    container_name: productmanager.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - "ConnectionStrings:ProductManagerConnection=Server=productmanagerdb;Database=ProductManagerDb;User Id=sa;Password=SwN12345678;TrustServerCertificate=Yes"
    depends_on:
      - productmanagerdb
    ports:
      - "8080"
      - "8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro